"""intial

Revision ID: e7085934aeda
Revises: 
Create Date: 2021-03-10 14:01:28.622755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7085934aeda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('restaurant', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurants_email'), 'restaurants', ['email'], unique=True)
    op.create_index(op.f('ix_restaurants_restaurant'), 'restaurants', ['restaurant'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurants_restaurant'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_email'), table_name='restaurants')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
